# Generated by Django 4.0.2 on 2022-02-17 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapp.products')),
            ],
        ),
        migrations.AlterModelOptions(
            name='purchases',
            options={'verbose_name_plural': 'Purchases'},
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='count',
        ),
        migrations.RemoveField(
            model_name='purchases',
            name='product',
        ),
        migrations.AddField(
            model_name='purchases',
            name='product',
            field=models.ManyToManyField(through='myapp.ProductPurchase', to='myapp.Products'),
        ),
        migrations.AlterField(
            model_name='purchases',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='returns',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='productpurchase',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.purchases'),
        ),
    ]
