# Generated by Django 4.0.2 on 2022-02-17 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('quantity_in_stock', models.IntegerField(default=0)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Goods',
                'ordering': ['name', 'price'],
            },
        ),
        migrations.CreateModel(
            name='GoodsCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_count', models.IntegerField(default=1)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='storeapp.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='myuser', to=settings.AUTH_USER_MODEL)),
                ('goods', models.ManyToManyField(through='storeapp.GoodsCount', to='storeapp.Goods')),
            ],
            options={
                'verbose_name_plural': 'Purchase',
                'ordering': ['customer', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='storeapp.purchase')),
            ],
            options={
                'verbose_name_plural': 'Return',
                'ordering': ['purchase', 'time'],
            },
        ),
        migrations.AddField(
            model_name='goodscount',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='storeapp.purchase'),
        ),
    ]
